"""add critic score columns to movies

Revision ID: 2be34eb24448
Revises: ad73b127f717
Create Date: 2026-09-08 10:00:15.648881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be34eb24448'
down_revision: Union[str, Sequence[str], None] = 'ad73b127f717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('rotten_tomatoes_score', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('metascore', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('imdb_rating', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('critic_scores_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'critic_scores_checked_at')
    op.drop_column('movies', 'imdb_rating')
    op.drop_column('movies', 'metascore')
    op.drop_column('movies', 'rotten_tomatoes_score')
    # ### end Alembic commands ###
