"""add data_anomalies table

Revision ID: 6b988c17ba6f
Revises: 2be34eb24448
Create Date: 2026-09-08 13:15:10.321901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b988c17ba6f'
down_revision: Union[str, Sequence[str], None] = '2be34eb24448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'rule_name')
    )
    op.create_index(op.f('ix_data_anomalies_movie_id'), 'data_anomalies', ['movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_anomalies_movie_id'), table_name='data_anomalies')
    op.drop_table('data_anomalies')
    # ### end Alembic commands ###
