"""add investigation fields to data_anomalies

Revision ID: 9659d7875ee0
Revises: d5bed2540e39
Create Date: 2026-09-12 17:09:00.734275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9659d7875ee0'
down_revision: Union[str, Sequence[str], None] = 'd5bed2540e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_anomalies', sa.Column('likely_data_error', sa.Boolean(), nullable=True))
    op.add_column('data_anomalies', sa.Column('suggested_correction', sa.Text(), nullable=True))
    op.add_column('data_anomalies', sa.Column('investigation_source_note', sa.Text(), nullable=True))
    op.add_column('data_anomalies', sa.Column('investigated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_anomalies', 'investigated_at')
    op.drop_column('data_anomalies', 'investigation_source_note')
    op.drop_column('data_anomalies', 'suggested_correction')
    op.drop_column('data_anomalies', 'likely_data_error')
    # ### end Alembic commands ###
