"""add audience demographics columns to movies

Revision ID: a3286ebc3a03
Revises: af7b91fe392e
Create Date: 2026-09-08 21:30:56.701432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3286ebc3a03'
down_revision: Union[str, Sequence[str], None] = 'af7b91fe392e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('demographic_percent_female', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('demographic_percent_male', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('demographic_percent_under_25', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('demographic_percent_25_and_over', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('demographic_race_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('movies', sa.Column('demographic_source_note', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('demographics_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'demographics_checked_at')
    op.drop_column('movies', 'demographic_source_note')
    op.drop_column('movies', 'demographic_race_breakdown')
    op.drop_column('movies', 'demographic_percent_25_and_over')
    op.drop_column('movies', 'demographic_percent_under_25')
    op.drop_column('movies', 'demographic_percent_male')
    op.drop_column('movies', 'demographic_percent_female')
    # ### end Alembic commands ###
