"""Add studio_slug to movies and studio_stock_prices table

Revision ID: a8add591d7cb
Revises: a3286ebc3a03
Create Date: 2026-09-11 17:36:14.637993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8add591d7cb'
down_revision: Union[str, Sequence[str], None] = 'a3286ebc3a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studio_stock_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('close_usd', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'week_start_date', 'source')
    )
    op.create_index(op.f('ix_studio_stock_prices_ticker'), 'studio_stock_prices', ['ticker'], unique=False)
    op.add_column('movies', sa.Column('studio_slug', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_movies_studio_slug'), 'movies', ['studio_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_studio_slug'), table_name='movies')
    op.drop_column('movies', 'studio_slug')
    op.drop_index(op.f('ix_studio_stock_prices_ticker'), table_name='studio_stock_prices')
    op.drop_table('studio_stock_prices')
    # ### end Alembic commands ###
