"""add lifetime gross columns to movies

Revision ID: ad73b127f717
Revises: f6a71ba340ea
Create Date: 2026-09-07 22:46:55.784855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad73b127f717'
down_revision: Union[str, Sequence[str], None] = 'f6a71ba340ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('domestic_gross_usd', sa.BigInteger(), nullable=True))
    op.add_column('movies', sa.Column('worldwide_gross_usd', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'worldwide_gross_usd')
    op.drop_column('movies', 'domestic_gross_usd')
    # ### end Alembic commands ###
