"""add industry_weekly_gross table

Revision ID: af7b91fe392e
Revises: 052ccd88360d
Create Date: 2026-09-08 21:19:48.602724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7b91fe392e'
down_revision: Union[str, Sequence[str], None] = '052ccd88360d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_weekly_gross',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('total_gross_usd', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start_date', 'source')
    )
    op.create_index(op.f('ix_industry_weekly_gross_week_start_date'), 'industry_weekly_gross', ['week_start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_industry_weekly_gross_week_start_date'), table_name='industry_weekly_gross')
    op.drop_table('industry_weekly_gross')
    # ### end Alembic commands ###
