"""Add request_latency_samples table

Revision ID: db9b2968c0b4
Revises: a8add591d7cb
Create Date: 2026-09-12 15:59:14.963161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9b2968c0b4'
down_revision: Union[str, Sequence[str], None] = 'a8add591d7cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_latency_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('route_template', sa.String(length=200), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_latency_samples_created_at'), 'request_latency_samples', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_latency_samples_route_template'), 'request_latency_samples', ['route_template'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_latency_samples_route_template'), table_name='request_latency_samples')
    op.drop_index(op.f('ix_request_latency_samples_created_at'), table_name='request_latency_samples')
    op.drop_table('request_latency_samples')
    # ### end Alembic commands ###
