"""init schema

Revision ID: f6a71ba340ea
Revises: 
Create Date: 2026-09-07 21:25:41.775934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6a71ba340ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('training_data_cutoff_date', sa.Date(), nullable=True),
    sa.Column('feature_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluation_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('original_title', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('budget_usd', sa.BigInteger(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('belongs_to_collection_tmdb_id', sa.Integer(), nullable=True),
    sa.Column('is_sequel', sa.Boolean(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.Text(), nullable=True),
    sa.Column('popularity_tmdb_snapshot', sa.Float(), nullable=True),
    sa.Column('popularity_snapshot_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_tmdb_id'), 'movies', ['tmdb_id'], unique=True)
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('known_for_department', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_tmdb_id'), 'people', ['tmdb_id'], unique=True)
    op.create_table('movie_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('cast_order', sa.Integer(), nullable=True),
    sa.Column('character_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'person_id', 'role', 'cast_order')
    )
    op.create_index(op.f('ix_movie_credits_movie_id'), 'movie_credits', ['movie_id'], unique=False)
    op.create_index(op.f('ix_movie_credits_person_id'), 'movie_credits', ['person_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('predicted_opening_weekend_usd', sa.Numeric(), nullable=True),
    sa.Column('predicted_domestic_total_usd', sa.Numeric(), nullable=True),
    sa.Column('predicted_worldwide_total_usd', sa.Numeric(), nullable=True),
    sa.Column('predicted_decay_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_model_run_id'), 'predictions', ['model_run_id'], unique=False)
    op.create_index(op.f('ix_predictions_movie_id'), 'predictions', ['movie_id'], unique=False)
    op.create_table('weekly_gross_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=True),
    sa.Column('territory', sa.String(length=20), nullable=False),
    sa.Column('weekend_gross_usd', sa.BigInteger(), nullable=True),
    sa.Column('cumulative_gross_usd', sa.BigInteger(), nullable=True),
    sa.Column('theater_count', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'week_number', 'territory', 'source')
    )
    op.create_index(op.f('ix_weekly_gross_observations_movie_id'), 'weekly_gross_observations', ['movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_gross_observations_movie_id'), table_name='weekly_gross_observations')
    op.drop_table('weekly_gross_observations')
    op.drop_index(op.f('ix_predictions_movie_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_model_run_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_movie_credits_person_id'), table_name='movie_credits')
    op.drop_index(op.f('ix_movie_credits_movie_id'), table_name='movie_credits')
    op.drop_table('movie_credits')
    op.drop_index(op.f('ix_people_tmdb_id'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_movies_tmdb_id'), table_name='movies')
    op.drop_table('movies')
    op.drop_table('model_runs')
    # ### end Alembic commands ###
